version: '3'
services:

  svelte:
    build: svelte
    volumes:
      - ./svelte:/usr/src/app
      - /usr/src/app/node_modules
      # - "~/.gitconfig:/etc/gitconfig"
    container_name: svelte-dev
    restart: always
    stdin_open: true
    ports:
      - "3000:3000"
    expose:
      - "3000"

  svelte-prod:
    build:
      context: svelte
      dockerfile: ./Dockerfile.prod
    container_name: svelte-prod
    restart: always
    ports:
      - "80:80"
    expose:
      - "80"

  api:
    depends_on:
      - postgres
    image: strapi/strapi:3.6.8-node14
    restart: unless-stopped
    container_name: strapi_cms
    environment:
      APP_NAME: strapi-app
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_DB: ${DATABASE_DB}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: "false"
    ports:
      - 8080:1337
    volumes:
      # - ./cms:/srv/cms
      - ./strapi:/srv/app

  postgres:
    container_name: postgres_db_2
    restart: unless-stopped
    image:  postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME} #optional (specify default database instead of $POSTGRES_USER)
      PGPORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image:  dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PW}
      MAX_LOGIN_ATTEMPTS: 5
      # PGADMIN_LISTEN_PORT=: ${PGADMIN_LISTEN_PORT}
    ports:
      - "5050:80"
    restart: always

volumes:
  postgres-data:
  cms:

networks:
  react-express:
  express-mongo:
