# Generated by Django 3.2.13 on 2022-07-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crib', '0003_auto_20220630_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.IntegerField(choices=[('default', 'default'), ('homepage', 'homepage')], db_column='page_template', default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='template',
            field=models.IntegerField(choices=[('default', 'default'), ('homepage', 'homepage')], db_column='post_template', default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(db_column='page_slug', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(db_column='page_title', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(db_column='post_slug', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_column='post_title', max_length=300, unique=True),
        ),
    ]
