# Generated by Django 3.2.13 on 2022-07-01 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crib', '0004_auto_20220701_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='template',
        ),
    ]
