# Generated by Django 3.2.13 on 2022-07-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crib', '0005_remove_post_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.IntegerField(choices=[(0, 'default'), (1, 'homepage')], db_column='page_template', default=0),
        ),
    ]
