# Generated by Django 3.2.13 on 2022-07-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crib', '0006_alter_page_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('default', 'default'), ('homepage', 'homepage')], db_column='page_template', default='default', max_length=40),
        ),
    ]
