# Generated by Django 3.2.13 on 2022-07-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crib', '0007_alter_page_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], db_column='page_status', default='draft', max_length=40),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('default', 'Default'), ('homepage', 'Homepage')], db_column='page_template', default='default', max_length=40),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], db_column='post_status', default='draft', max_length=40),
        ),
    ]
