# Generated by Django 3.2.13 on 2022-07-02 22:13

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crib', '0008_auto_20220702_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeaterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='repeater_title', max_length=300, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(db_column='description_content')),
                ('page_id', models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='crib.page')),
            ],
            options={
                'ordering': ['title'],
                'managed': True,
            },
        ),
    ]
