# Generated by Django 3.2.13 on 2022-07-03 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crib', '0012_auto_20220703_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repeater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(db_column='membership_date_joined')),
                ('invite_reason', models.CharField(db_column='membership_invite_reason', max_length=64)),
                ('template', models.CharField(choices=[('default', 'Default'), ('homepage', 'Homepage')], db_column='membership_template', default='default', max_length=40)),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='membership_updated_on')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], db_column='membership_status', default='draft', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RepeaterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('members', models.ManyToManyField(through='crib.Repeater', to='crib.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='person',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.AddField(
            model_name='repeater',
            name='Repeatergroup',
            field=models.ForeignKey(db_column='membership_group', on_delete=django.db.models.deletion.CASCADE, to='crib.repeatergroup'),
        ),
        migrations.AddField(
            model_name='repeater',
            name='person',
            field=models.ForeignKey(db_column='membership_person', on_delete=django.db.models.deletion.CASCADE, to='crib.person'),
        ),
    ]
