# Generated by Django 3.2.13 on 2022-07-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crib', '0013_auto_20220703_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeater',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='repeater',
            name='invite_reason',
        ),
        migrations.RemoveField(
            model_name='repeater',
            name='status',
        ),
        migrations.RemoveField(
            model_name='repeater',
            name='template',
        ),
        migrations.RemoveField(
            model_name='repeater',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='repeater',
            name='repeater_content2',
            field=models.TextField(blank=True, db_column='repeater_content2'),
        ),
    ]
