# Generated by Django 3.2.13 on 2022-07-03 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crib', '0014_auto_20220703_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.IntegerField(db_column='meta_id', primary_key=True, serialize=False)),
                ('key', models.CharField(db_column='meta_key', max_length=255)),
                ('value', models.TextField(db_column='meta_value')),
                ('post', models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='crib.page')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
