# Generated by Django 3.2.13 on 2022-07-03 13:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crib', '0015_pagemeta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagemeta',
            old_name='post',
            new_name='page',
        ),
        migrations.RemoveField(
            model_name='pagemeta',
            name='key',
        ),
        migrations.RemoveField(
            model_name='pagemeta',
            name='value',
        ),
        migrations.AddField(
            model_name='pagemeta',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='description_content'),
        ),
        migrations.AddField(
            model_name='pagemeta',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='pagemeta',
            name='title',
            field=models.CharField(blank=True, db_column='repeater_title', max_length=300),
        ),
    ]
