# Generated by Django 3.2.13 on 2022-07-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crib', '0016_auto_20220703_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemeta',
            name='description',
            field=models.TextField(blank=True, db_column='description_content'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
