# Generated by Django 3.2.13 on 2022-07-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crib', '0018_auto_20220703_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagemeta',
            old_name='page',
            new_name='page_id',
        ),
    ]
