# Generated by Django 3.2.13 on 2022-07-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crib', '0019_rename_page_pagemeta_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemeta',
            name='image',
            field=models.ImageField(blank=True, upload_to='page-meta'),
        ),
    ]
