# Generated by Django 3.2.13 on 2022-07-03 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crib', '0020_alter_pagemeta_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_column='meta_title', max_length=200)),
                ('description', models.TextField(blank=True, db_column='meta_content', max_length=400)),
                ('image', models.ImageField(blank=True, upload_to='post-meta')),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='crib.post')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='repeater',
            name='Repeatergroup',
        ),
        migrations.RemoveField(
            model_name='repeater',
            name='person',
        ),
        migrations.RemoveField(
            model_name='repeatergroup',
            name='members',
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='description',
            field=models.TextField(blank=True, db_column='meta_content', max_length=400),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='title',
            field=models.CharField(blank=True, db_column='meta_title', max_length=200),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Repeater',
        ),
        migrations.DeleteModel(
            name='RepeaterGroup',
        ),
    ]
