# Generated by Django 3.2.13 on 2022-07-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crib', '0021_auto_20220703_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagemeta',
            options={'managed': True, 'ordering': ['meta_order']},
        ),
        migrations.AlterModelOptions(
            name='postmeta',
            options={'managed': True, 'ordering': ['meta_order']},
        ),
        migrations.AddField(
            model_name='pagemeta',
            name='meta_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postmeta',
            name='meta_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
