# Generated by Django 3.2.13 on 2022-07-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crib', '0022_auto_20220703_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagemeta',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='postmeta',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='pagemeta',
            name='meta_order',
        ),
        migrations.RemoveField(
            model_name='postmeta',
            name='meta_order',
        ),
    ]
