name: Docker Image CI

# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
  REPO_NAME: 'github-test'
  #${{secrets.REPO_NAME}}
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:

  #login:
  #  runs-on: ubuntu-latest
   # steps:
    #  -
     #   name: Login to Docker Hub
      #  uses: docker/login-action@v2
       # with:
        #  username: ${{ secrets.DOCKERHUB_USERNAME }}
         # password: ${{ secrets.DOCKERHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cicd-test:latest 
