name: Docker Compose Image CI

# env variables
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
  REPO_NAME: 'github-test'
  #${{secrets.REPO_NAME}} 

  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DJANGO_SETTINGS_MODULE: app_name.settings.dev
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  PORT: 8000
  PG_DB: ${{ secrets.PG_DB }}
  PG_PASS: ${{ secrets.PG_PASS }}
  PG_USER: ${{ secrets.USER }}
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:  
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up -d
      - name: Sleep
        uses: jakejarvis/wait-action@master
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cicdtest:latest
 

