name: Docker Compose Image CI

# env variables
env:
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
  REPO_NAME: 'github-test'
  #${{secrets.REPO_NAME}} 

  DATABASE_URL: ${{ secrets.DATABASE_URL }} 
  SECRET_KEY: ${{ secrets.SECRET_KEY }} 
  PG_DB: ${{ secrets.PG_DB }}
  PG_PASS: ${{ secrets.PG_PASS }}
  PG_USER: ${{ secrets.USER }}
  
on:
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
 
jobs:  
  docker:
    runs-on: ubuntu-latest
    steps:
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Checkout 
        uses: actions/checkout@v1
        
      - name: Docker compose version
        run: docker-compose -v 
        
      - name: Build the docker-compose stack  
        run: docker-compose up -d --build -no-cache --remove-orphans
        
      - name: Docker image list
        run: docker image ls
        
      - name: Dockerhub push 
        run: docker-compose push
        
      #- name: Sleep
      #  uses: jakejarvis/wait-action@master 
