name: Docker Compose Image CI

# env variables
env:
  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_TOKEN: ${{secrets.DOCKERHUB_TOKEN}} 
  DOCKER_HOST: ssh://root:${{ secrets.DOCKER_HOST_PASSWORD}}@168.235.69.236
  
  #HOST: 0.0.0.0
  #PORT: 1337
  DATABASE_CLIENT: postgres
  DATABASE_NAME: db_strapi
  DATABASE_HOST: postgres
  DATABASE_PORT: 5432
  DATABASE_USERNAME: my_user
  DATABASE_PASSWORD: my_root_password
  DATABASE_DB: strapi 
  POSTGRES_USER: strapi
  POSTGRES_PW: strapi
  POSTGRES_DB: postgres
  PGADMIN_MAIL: user@domain.com
  PGADMIN_PW: SuperSecret

  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:  
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Checkout 
        uses: actions/checkout@v3
        
      - name: Docker context ls
        run: docker context ls 
        
      - name: check export
        run: export
        
      - name: Docker context
        run: docker context create \
             --docker host=${{secrets.DOCKER_HOST}} \ 
             remote 
        
      - name: Docker context Switch
        run: docker context use remote
        
      #- name: Docker compose rm
      #  run: docker compose rm -f
        
      #- name: Docker compose pull new images
      #  run: docker compose pull
      
     
        
      - name: Docker compose version
        run: docker compose -v 
        
      - name: Build the docker-compose stack  
        run: docker compose ‐‐context remote up -d --build --remove-orphans
        
      - name: Docker image list
        run: docker image ls
        
      - name: Dockerhub push 
        run: docker compose push
        
      #- name: Sleep
      #  uses: jakejarvis/wait-action@master 
